(deftheme idea-darkula-mw
  "Customize idea-darkula 2019-11-01.")

(custom-theme-set-faces
 'idea-darkula-mw
 '(cursor ((t (:background "#bbbbbb"))))
 '(region ((t (:background "#214283"))))
 '(vertical-border ((t (:foreground "#555555"))))
 '(fringe ((t (:foreground "#555555"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#287BDE"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#287BDE" :inherit (link)))))
 '(isearch ((t (:background "#214283" :box (:line-width -1 :color "#bbbbbb")))))
 '(lazy-highlight ((t (:background "#32593d" :box (:line-width -1 :color "#3c704b")))))
 '(tooltip ((t (:foreground "gray25" :background "khaki2" :inherit variable-pitch))))
 '(mode-line ((t (:box (:line-width -1 :color "#464646") :weight bold :foreground "#bbbbbb" :background "#3c3f41"))))
 '(mode-line-inactive ((t (:style released-button :inherit (mode-line) :weight normal))))
 '(hl-line ((t (:background "#323232"))))
 '(font-lock-comment-face ((t (:foreground "#808080"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#808080"))))
 '(font-lock-doc-face ((t (:foreground "#629755" :italic t))))
 '(font-lock-keyword-face ((t (:foreground "#CC7832"))))
 '(font-lock-preprocessor-face ((t (:foreground "green"))))
 '(font-lock-string-face ((t (:foreground "#6A8759"))))
 '(font-lock-type-face ((t (:foreground "#CC7832"))))
 '(font-lock-builtin-face ((t (:foreground "#CC7832"))))
 '(font-lock-function-name-face ((t (:foreground "#FFC66D"))))
 '(font-lock-constant-face ((t (:foreground "#9876AA" :italic t))))
 '(font-lock-warning-face ((t (:foreground "red"))))
 '(c-annotation-face ((t (:foreground "#BBB529"))))
 '(info-menu-header ((t (:foreground "white"))))
 '(info-title-1 ((t (:foreground "white"))))
 '(info-title-2 ((t (:foreground "white"))))
 '(info-title-3 ((t (:foreground "white"))))
 '(info-title-4 ((t (:foreground "white"))))
 '(helm-selection ((t (:background "yellow" :foreground "black"))))
 '(helm-ff-directory ((t (:foreground "#ffffff" :background "MidnightBlue"))))
 '(company-tooltip ((t (:foreground "#bbbbbb" :background "#3c3f41"))))
 '(company-tooltip-selection ((t (:background "#0052a4"))))
 '(company-tooltip-search ((t (:inherit isearch))))
 '(company-tooltip-mouse ((t (:background "#4a4e4f"))))
 '(company-tooltip-common ((t (:foreground "#d17ad6"))))
 '(company-tooltip-annotation ((t (:inherit company-tooltip-common))))
 '(company-scrollbar-fg ((t (:background "#5b5d5e"))))
 '(company-scrollbar-bg ((t (:background "#3b3f40"))))
 '(company-preview ((t (:inherit region))))
 '(company-preview-common ((t (:inherit company-preview :foreground "#d17ad6"))))
 '(company-preview-search ((t (:inherit isearch))))
 '(default ((t (:underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#A9B7C6" :background "#2B2B2B" :stipple nil :inherit nil)))))

(provide-theme 'idea-darkula-mw)
